/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author AJIT BHOLE
 */
public class UserJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserJFrame.class.getName());

    /**
     * Creates new form UserJFrame
     */
    public UserJFrame() {
        initComponents();
        setupAgeSpinner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        firstName = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JLabel();
        continent = new javax.swing.JLabel();
        experience = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jSpinnerAge = new javax.swing.JSpinner();
        jScrollPaneExpTextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        continentComboBox = new javax.swing.JComboBox<>();
        phoneNumberText = new javax.swing.JTextField();
        photo = new javax.swing.JLabel();
        photoTextField = new javax.swing.JTextField();
        uploadButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstName.setText("First Name :");

        lastName.setText("Last Name :");

        gender.setText(" Gender :");

        age.setText(" Age :");

        phoneNumber.setText("Phone Number :");

        continent.setText("Continent :");

        experience.setText("Experience :");

        firstNameText.addActionListener(this::firstNameTextActionPerformed);

        lastNameText.addActionListener(this::lastNameTextActionPerformed);

        buttonGroup3.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");

        buttonGroup3.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");

        jSpinnerAge.setPreferredSize(new java.awt.Dimension(74, 28));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPaneExpTextArea.setViewportView(jTextArea1);

        continentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Europe", "Asia", "North America", "South America", "Africa", "Ausralia" }));
        continentComboBox.addActionListener(this::continentComboBoxActionPerformed);

        phoneNumberText.setToolTipText("789-456-123");

        photo.setText("Photo :");

        uploadButton.setText("Upload");
        uploadButton.addActionListener(this::uploadButtonActionPerformed);

        submitButton.setText("Submit");
        submitButton.addActionListener(this::submitButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(firstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(experience, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(continent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gender))
                            .addComponent(phoneNumber)
                            .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneExpTextArea)
                            .addComponent(photoTextField)
                            .addComponent(phoneNumberText)
                            .addComponent(lastNameText)
                            .addComponent(firstNameText))
                        .addGap(18, 18, 18)
                        .addComponent(uploadButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(submitButton)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(jRadioButtonMale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonFemale)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(jSpinnerAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumber)
                    .addComponent(phoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continent)
                    .addComponent(continentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(experience)
                    .addComponent(jScrollPaneExpTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(photo)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(photoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void continentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_continentComboBoxActionPerformed

    private void setupAgeSpinner() {
    // start value, min, max, step -> starts at 18, can never go below 1 or above 120
    jSpinnerAge.setModel(new javax.swing.SpinnerNumberModel(18, 0, 120, 1));

    // "#" = plain integer display (no decimals or commas)
    javax.swing.JSpinner.NumberEditor editor =
        new javax.swing.JSpinner.NumberEditor(jSpinnerAge, "#");
    jSpinnerAge.setEditor(editor);

    javax.swing.JFormattedTextField tf = editor.getTextField();
    javax.swing.text.NumberFormatter formatter =
        (javax.swing.text.NumberFormatter) tf.getFormatter(); 

    formatter.setAllowsInvalid(false);      // blocks letters, "-", and out-of-range numbers
    formatter.setCommitsOnValidEdit(true);  // typed value is applied immediately, no Enter needed

    // Select the whole number when the field is clicked, so typing replaces it
    tf.addFocusListener(new java.awt.event.FocusAdapter() {
        @Override
        public void focusGained(java.awt.event.FocusEvent e) {
            javax.swing.SwingUtilities.invokeLater(tf::selectAll);
        }
    });
}
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
    // TODO add your handling code here:
    
    String errorTitle = "Oops";
    try{
        
        String firstName = firstNameText.getText().trim();
        String lastName = lastNameText.getText().trim();
        String phone = phoneNumberText.getText().trim();
        String continentSel = (String) continentComboBox.getSelectedItem();
        int ageValue = (int) jSpinnerAge.getValue();
        String experienceText = jTextArea1.getText().trim();
        String photoPath = photoTextField.getText().trim();
        
        // Determine selected gender from the radio button group
        String genderSel = null;
        if (jRadioButtonFemale.isSelected()) {
            genderSel = "Female";
        } else if (jRadioButtonMale.isSelected()) {
            genderSel = "Male";
        }
        
         // --- Basic validations ---
        if (firstName.isEmpty() || lastName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "First and Last name are required.", errorTitle,
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (genderSel == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a gender.", errorTitle,
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!phone.matches("\\d{3}-\\d{3}-\\d{3}")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Phone number must be in format 789-456-123.", errorTitle,
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
         // --- Build a summary to confirm the data was captured correctly ---
        String summary = "First Name: " + firstName
            + "\nLast Name: " + lastName
            + "\nGender: " + genderSel
            + "\nAge: " + ageValue
            + "\nPhone: " + phone
            + "\nContinent: " + continentSel
            + "\nExperience: " + experienceText
            + "\nPhoto: " + photoPath;
        
         javax.swing.ImageIcon dialogIcon = null;
        if (!photoPath.isEmpty()) {
            try {
                javax.swing.ImageIcon rawIcon = new javax.swing.ImageIcon(photoPath);
                java.awt.Image scaled = rawIcon.getImage().getScaledInstance(
                    120, 120, java.awt.Image.SCALE_SMOOTH);
                dialogIcon = new javax.swing.ImageIcon(scaled);
            } catch (Exception ex) {
                logger.log(java.util.logging.Level.WARNING, "Could not load image for dialog", ex);
            }
        }

        if (ageValue < 18) {
            javax.swing.JOptionPane.showMessageDialog(this,
            "You must be at least 18 years old to submit.", errorTitle,
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this, summary,
            "Submitted Successfully",
            javax.swing.JOptionPane.INFORMATION_MESSAGE, dialogIcon);
        
        
        
        
        
    }
    catch(Exception ex){
    
         logger.log(java.util.logging.Level.SEVERE, "Error submitting form", ex);
        javax.swing.JOptionPane.showMessageDialog(this,
            "Something went wrong: " + ex.getMessage(), errorTitle,
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    
    
    }//GEN-LAST:event_submitButtonActionPerformed

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    fileChooser.setDialogTitle("Select a Photo");

    // Restrict to common image types
    javax.swing.filechooser.FileNameExtensionFilter filter =
        new javax.swing.filechooser.FileNameExtensionFilter(
            "Image files (*.jpg, *.jpeg, *.png, *.gif)", "jpg", "jpeg", "png", "gif");
    fileChooser.setFileFilter(filter);

    int result = fileChooser.showOpenDialog(this);
    
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        java.io.File selectedFile = fileChooser.getSelectedFile();
        photoTextField.setText(selectedFile.getAbsolutePath());
    }
        
    }//GEN-LAST:event_uploadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel continent;
    private javax.swing.JComboBox<String> continentComboBox;
    private javax.swing.JLabel experience;
    private javax.swing.JLabel firstName;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel gender;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPaneExpTextArea;
    private javax.swing.JSpinner jSpinnerAge;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastName;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel phoneNumber;
    private javax.swing.JTextField phoneNumberText;
    private javax.swing.JLabel photo;
    private javax.swing.JTextField photoTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
